language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

install: pip install -r requirements_dev.txt

script:
  - flake8
  - pydocstyle pact
  - tox --develop

jobs:
  include:
    - stage: package
      language: ruby
      python: "2.7"
      rvm: "2.2"
      script:
        - ruby --version
        - bundler --version
        - make package
