language:
  - python
  - ruby

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

rvm: "2.2"

sudo: false

install: pip install -r requirements_dev.txt

script:
  - flake8
  - pydocstyle pact
  - tox --develop

after_success:
  - ruby --version
  - bundler --version
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then make package; fi

deploy:
  - provider: pypi
    username: mkbalvanz
    password:
      secure: FQv38ztxAcgQMwjsL/WlOAZHP+Jtye1e51xMhgFZh4lfLDFlglGhaW7L8WGlSU2w4X0Vs7frdOxcyarwdHJnXCau06D6F6AAGVqGBAIw79Z5IOY68twskBDKjGD8yha2Bn9XEoR7Nmx36okxRikS7m5gPTRLcbvevm6hPowZoJCr4pVI0FrWKn2a0pM1tggxo8BwL8pM+lervy045A2FHRqX//2gE587+kBGTaO5ef2uKJVEAFUENWdHRkd3ht1d1XhgD2tfgy/u9OH66fFZQfRZJXvKMccBSgLbSQdKnhIZCylXi3S0/zPKQXWOKtAHcTtWg10bsaaWC6fNeIZyA8jCWhHG42+my1wR5cIuNUg3LLkLBDTTExdg5e3ZwvF4tp4qvzYjru1ALP38lyzHTa8AknlWZ6ReW5ef0PQvYH2YTQp37fR67hEWMFeY/o7vnwe+EwAXPlon1Bh+06RUNz+lrnvXyNRuhHU8RKEjjrfSGB8lMdu8fO+Lo+j5H/WfOka9L88jjb+1qJvLXoeGR2ON0hxJnc4S8VU8EdV5nA9FpfcqD1WDv7Z2LAIVChrnlHFa4ACXuIMQoAeDimss/yPFlwch23/LAtYWN5KU7crwss6dw0JZuZOMLzQ2+/+8f+b7fcp69VYLQ/5y+wL0B16zvOfw0ipN/sS58hP3U70=
    on:
      repo: pact-foundation/pact-python
      python: "2.7"
      tags: true
    server: https://testpypi.python.org/pypi
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: FQDAZNYQ0w59V8XIhc8qalp/iWywdQS/pNVfcsHD5NaiADY5d7IUdoiO3imoPkuAgiYhyR4ZpgqVVcGGKSY6iMkxh8cDO9lmmnm3lHj06gO9MHB8chf4I+U1Hkj0+PNhYPpLhpCc0jynszk96dCusaaIIPUO2tcSVKO79jVEBrL8P+jMSLsAdVGahgHbHP5ClfCfbzi2oFcKq8MDLiSKxg/1XHpb5tzOC/tG0X/Jnw3wULOr5ne8ESqnQP7XwZ4//WUphA9jGG//T7vYHa723r1mil7ehX2J5vpMdDHuKnl1mUJhwprELc6ZyzAXUnZsU8tYkaBlhMVmEwd+F444e6y44DB7sIuF6bsHS71fuWA60xRZ5wuJr6Vg0MDn1Tcaw8yzg65XQoWMLmYuaRieCSTppmqDLByC0In47zDjOvhsNX0Xonjy8D4xNsndT/TsxtFnz6SNEEFwf1PAvwoKZ9rbHCsP4ZsK+NkQ0tzCWA/8FJ0bnFo+yEiqlmnP2bW2jCfDjT4F5fnSYi4l1wY4bEbXUSYmuc2wSrQcsVZDG143nwtYg3AwwKPpMsQTlU1fYxndlQ7XNbTV8/6bPxcA5p1MGFqbxTOAzfboKSTEesuKZMGzs7wGAsF8x6F9ZnIaLCgMMyM3mne/yrfhVIgcAdINMeX+DZa6VEZFtbPv4pM=
    file: dist/pact-python-*.tar.gz
    file_glob: true
    on:
      repo: pact-foundation/pact-python
      python: "2.7"
      tags: true
    skip_cleanup: true
